name: checks
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          pip install pre-commit
          pip install -e .
          pip install -r requirements.dev.txt
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    name: test py=${{ matrix.py_version }} django=${{ matrix.django_version }} drf=${{ matrix.drf_version }}
    strategy:
      fail-fast: false
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        drf_version: ["3.15", "3.16", "3.17"]
        django_version:
          - "4.2" # LTS
          - "5.2" # LTS
          - "6" # current major version
        exclude:
          # exclude new django versions with old python versions
          - py_version: "3.10"
            django_version: "6"
          - py_version: "3.11"
            django_version: "6"
          # exclude old django versions with new python versions
          - py_version: "3.14"
            django_version: "4.2"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.py_version }}"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.dev.txt
      - name: Install dependencies
        run: |
          pip install .[django,djangorestframework] -r requirements.dev.txt django==${{ matrix.django_version }} djangorestframework==${{ matrix.drf_version }}
      - name: Run tests
        run: pytest
